### ISSUE TITLE
Errno 2 on VLC

### ISSUE THREAD

**Issue by Shruti-codes** [Raghav714/Cable-TV#2]
" No such file or directory: 'vlc': 'vlc' "

VLC is already installed though!

**Comment by Raghav714** [comment]
please provide the screenshot of the error. In case you mistakenly edited the "stream.py" then unzip the download repo again and run it. 

`vlc --version` run this command in terminal and please paste the output here

**Comment by Shruti-codes** [comment]
![Screenshot 2020-07-13 at 10 09 04 PM](https://user-images.githubusercontent.com/30073239/87330055-9f13fa00-c555-11ea-8c14-f8430ebadd31.png)

**Comment by Raghav714** [comment]
It looks like you need to update ur VLC player to version 3.0.8.
