### ISSUE TITLE
Authentication Protocols not supported

### ISSUE THREAD

**Issue by aaditagarwal** [Raghav714/Cable-TV#3]
When executing the file, it outputs an authentication error for few channels in the provided list. (Ex: Sony Ten 1, Movies Now)
Screenshot: 
![Screenshot from 2020-07-12 17-15-43](https://user-images.githubusercontent.com/43968238/87245623-634d3780-c464-11ea-896e-24ec23c48016.png)

Common non-subscription channels such as DD news work perfect.

Also few of the subscription channels such as Zee Cinema work fine even with the authentication error.
![Screenshot from 2020-07-12 17-25-31](https://user-images.githubusercontent.com/43968238/87245667-d6ef4480-c464-11ea-8a41-ac1d9da4a2ea.png)
![Screenshot from 2020-07-12 17-25-34](https://user-images.githubusercontent.com/43968238/87245669-d9519e80-c464-11ea-9fab-f8c74a563bc7.png)

**Comment by Raghav714** [comment]
It looks like the API of these channels is updated or changed. In that case, we can update those API in this repository code.
